//
// /tmp/gl_es.c
//
// Autogenerated from gl.xml
//
// Mike Larson
//
// January 2026
//

#include "glcorearb.h"

#include "glm_context.h"

extern GLMContext _ctx;
extern void mgl_lazy_init(void);

#define GET_CONTEXT()   (mgl_lazy_init(), _ctx)

void glReadBuffer(GLenum src)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.read_buffer(ctx, src);
}

void glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_range_elements(ctx, mode, start, end, count, type, indices);
}

void glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_image3D(ctx, target, level, internalformat, width, height, depth, border, format, type, pixels);
}

void glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_sub_image3D(ctx, target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels);
}

void glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.copy_tex_sub_image3D(ctx, target, level, xoffset, yoffset, zoffset, x, y, width, height);
}

void glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.compressed_tex_image3D(ctx, target, level, internalformat, width, height, depth, border, imageSize, data);
}

void glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.compressed_tex_sub_image3D(ctx, target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data);
}

void glGenQueries(GLsizei n, GLuint *ids)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.gen_queries(ctx, n, ids);
}

void glDeleteQueries(GLsizei n, const GLuint *ids)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.delete_queries(ctx, n, ids);
}

GLboolean  glIsQuery(GLuint id)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_query(ctx, id);
}

void glBeginQuery(GLenum target, GLuint id)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.begin_query(ctx, target, id);
}

void glEndQuery(GLenum target)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.end_query(ctx, target);
}

void glGetQueryiv(GLenum target, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_queryiv(ctx, target, pname, params);
}

void glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_query_objectuiv(ctx, id, pname, params);
}

GLboolean  glUnmapBuffer(GLenum target)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.unmap_buffer(ctx, target);
}

void glGetBufferPointerv(GLenum target, GLenum pname, void **params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_buffer_pointerv(ctx, target, pname, params);
}

void glDrawBuffers(GLsizei n, const GLenum *bufs)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_buffers(ctx, n, bufs);
}

void glUniformMatrix2x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_matrix2x3fv(ctx, location, count, transpose, value);
}

void glUniformMatrix3x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_matrix3x2fv(ctx, location, count, transpose, value);
}

void glUniformMatrix2x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_matrix2x4fv(ctx, location, count, transpose, value);
}

void glUniformMatrix4x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_matrix4x2fv(ctx, location, count, transpose, value);
}

void glUniformMatrix3x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_matrix3x4fv(ctx, location, count, transpose, value);
}

void glUniformMatrix4x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_matrix4x3fv(ctx, location, count, transpose, value);
}

void glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.blit_framebuffer(ctx, srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter);
}

void glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.renderbuffer_storage_multisample(ctx, target, samples, internalformat, width, height);
}

void glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.framebuffer_texture_layer(ctx, target, attachment, texture, level, layer);
}

void *glMapBufferRange(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.map_buffer_range(ctx, target, offset, length, access);
}

void glFlushMappedBufferRange(GLenum target, GLintptr offset, GLsizeiptr length)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.flush_mapped_buffer_range(ctx, target, offset, length);
}

void glBindVertexArray(GLuint array)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_vertex_array(ctx, array);
}

void glDeleteVertexArrays(GLsizei n, const GLuint *arrays)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.delete_vertex_arrays(ctx, n, arrays);
}

void glGenVertexArrays(GLsizei n, GLuint *arrays)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.gen_vertex_arrays(ctx, n, arrays);
}

GLboolean  glIsVertexArray(GLuint array)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_vertex_array(ctx, array);
}

void glGetIntegeri_v(GLenum target, GLuint index, GLint *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_integeri_v(ctx, target, index, data);
}

void glBeginTransformFeedback(GLenum primitiveMode)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.begin_transform_feedback(ctx, primitiveMode);
}

void glEndTransformFeedback()
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.end_transform_feedback(ctx, );
}

void glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_buffer_range(ctx, target, index, buffer, offset, size);
}

void glBindBufferBase(GLenum target, GLuint index, GLuint buffer)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_buffer_base(ctx, target, index, buffer);
}

void glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.transform_feedback_varyings(ctx, program, count, varyings, bufferMode);
}

void glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_transform_feedback_varying(ctx, program, index, bufSize, length, size, type, name);
}

void glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_i_pointer(ctx, index, size, type, stride, pointer);
}

void glGetVertexAttribIiv(GLuint index, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_vertex_attrib_iiv(ctx, index, pname, params);
}

void glGetVertexAttribIuiv(GLuint index, GLenum pname, GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_vertex_attrib_iuiv(ctx, index, pname, params);
}

void glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_i4i(ctx, index, x, y, z, w);
}

void glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_i4ui(ctx, index, x, y, z, w);
}

void glVertexAttribI4iv(GLuint index, const GLint *v)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_i4iv(ctx, index, v);
}

void glVertexAttribI4uiv(GLuint index, const GLuint *v)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_i4uiv(ctx, index, v);
}

void glGetUniformuiv(GLuint program, GLint location, GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_uniformuiv(ctx, program, location, params);
}

GLint  glGetFragDataLocation(GLuint program, const GLchar *name)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_frag_data_location(ctx, program, name);
}

void glUniform1ui(GLint location, GLuint v0)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform1ui(ctx, location, v0);
}

void glUniform2ui(GLint location, GLuint v0, GLuint v1)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform2ui(ctx, location, v0, v1);
}

void glUniform3ui(GLint location, GLuint v0, GLuint v1, GLuint v2)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform3ui(ctx, location, v0, v1, v2);
}

void glUniform4ui(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform4ui(ctx, location, v0, v1, v2, v3);
}

void glUniform1uiv(GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform1uiv(ctx, location, count, value);
}

void glUniform2uiv(GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform2uiv(ctx, location, count, value);
}

void glUniform3uiv(GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform3uiv(ctx, location, count, value);
}

void glUniform4uiv(GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform4uiv(ctx, location, count, value);
}

void glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.clear_bufferiv(ctx, buffer, drawbuffer, value);
}

void glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.clear_bufferuiv(ctx, buffer, drawbuffer, value);
}

void glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.clear_bufferfv(ctx, buffer, drawbuffer, value);
}

void glClearBufferfi(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.clear_bufferfi(ctx, buffer, drawbuffer, depth, stencil);
}

GLubyte const  *glGetStringi(GLenum name, GLuint index)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_stringi(ctx, name, index);
}

void glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.copy_buffer_sub_data(ctx, readTarget, writeTarget, readOffset, writeOffset, size);
}

void glGetUniformIndices(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_uniform_indices(ctx, program, uniformCount, uniformNames, uniformIndices);
}

void glGetActiveUniformsiv(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_active_uniformsiv(ctx, program, uniformCount, uniformIndices, pname, params);
}

GLuint  glGetUniformBlockIndex(GLuint program, const GLchar *uniformBlockName)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_uniform_block_index(ctx, program, uniformBlockName);
}

void glGetActiveUniformBlockiv(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_active_uniform_blockiv(ctx, program, uniformBlockIndex, pname, params);
}

void glGetActiveUniformBlockName(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_active_uniform_block_name(ctx, program, uniformBlockIndex, bufSize, length, uniformBlockName);
}

void glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.uniform_block_binding(ctx, program, uniformBlockIndex, uniformBlockBinding);
}

void glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_arrays_instanced(ctx, mode, first, count, instancecount);
}

void glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_elements_instanced(ctx, mode, count, type, indicesinstancecount);
}

GLsync  glFenceSync(GLenum condition, GLbitfield flags)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.fence_sync(ctx, condition, flags);
}

GLboolean  glIsSync(GLsync sync)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_sync(ctx, sync);
}

void glDeleteSync(GLsync sync)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.delete_sync(ctx, sync);
}

GLenum  glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.client_wait_sync(ctx, sync, flags, timeout);
}

void glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.wait_sync(ctx, sync, flags, timeout);
}

void glGetInteger64v(GLenum pname, GLint64 *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_integer64v(ctx, pname, data);
}

void glGetSynciv(GLsync sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_synciv(ctx, sync, pname, count, length, values);
}

void glGetInteger64i_v(GLenum target, GLuint index, GLint64 *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_integer64i_v(ctx, target, index, data);
}

void glGetBufferParameteri64v(GLenum target, GLenum pname, GLint64 *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_buffer_parameteri64v(ctx, target, pname, params);
}

void glGenSamplers(GLsizei count, GLuint *samplers)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.gen_samplers(ctx, count, samplers);
}

void glDeleteSamplers(GLsizei count, const GLuint *samplers)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.delete_samplers(ctx, count, samplers);
}

GLboolean  glIsSampler(GLuint sampler)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_sampler(ctx, sampler);
}

void glBindSampler(GLuint unit, GLuint sampler)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_sampler(ctx, unit, sampler);
}

void glSamplerParameteri(GLuint sampler, GLenum pname, GLint param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sampler_parameteri(ctx, sampler, pname, param);
}

void glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint *param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sampler_parameteriv(ctx, sampler, pname, param);
}

void glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sampler_parameterf(ctx, sampler, pname, param);
}

void glSamplerParameterfv(GLuint sampler, GLenum pname, const GLfloat *param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sampler_parameterfv(ctx, sampler, pname, param);
}

void glGetSamplerParameteriv(GLuint sampler, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_sampler_parameteriv(ctx, sampler, pname, params);
}

void glGetSamplerParameterfv(GLuint sampler, GLenum pname, GLfloat *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_sampler_parameterfv(ctx, sampler, pname, params);
}

void glVertexAttribDivisor(GLuint index, GLuint divisor)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_divisor(ctx, index, divisor);
}

void glBindTransformFeedback(GLenum target, GLuint id)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_transform_feedback(ctx, target, id);
}

void glDeleteTransformFeedbacks(GLsizei n, const GLuint *ids)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.delete_transform_feedbacks(ctx, n, ids);
}

void glGenTransformFeedbacks(GLsizei n, GLuint *ids)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.gen_transform_feedbacks(ctx, n, ids);
}

GLboolean  glIsTransformFeedback(GLuint id)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_transform_feedback(ctx, id);
}

void glPauseTransformFeedback()
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.pause_transform_feedback(ctx, );
}

void glResumeTransformFeedback()
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.resume_transform_feedback(ctx, );
}

void glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_program_binary(ctx, program, bufSize, length, binaryFormat, binary);
}

void glProgramBinary(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_binary(ctx, program, binaryFormat, binarylength);
}

void glProgramParameteri(GLuint program, GLenum pname, GLint value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_parameteri(ctx, program, pname, value);
}

void glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum *attachments)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.invalidate_framebuffer(ctx, target, numAttachments, attachments);
}

void glInvalidateSubFramebuffer(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.invalidate_sub_framebuffer(ctx, target, numAttachments, attachments, x, y, width, height);
}

void glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_storage2D(ctx, target, levels, internalformat, width, height);
}

void glTexStorage3D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_storage3D(ctx, target, levels, internalformat, width, height, depth);
}

void glGetInternalformativ(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_internalformativ(ctx, target, internalformat, pname, count, params);
}

void glDispatchCompute(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.dispatch_compute(ctx, num_groups_x, num_groups_y, num_groups_z);
}

void glDispatchComputeIndirect(GLintptr indirect)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.dispatch_compute_indirect(ctx, indirect);
}

void glDrawArraysIndirect(GLenum mode, const void *indirect)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_arrays_indirect(ctx, mode, indirect);
}

void glDrawElementsIndirect(GLenum mode, GLenum type, const void *indirect)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_elements_indirect(ctx, mode, type, indirect);
}

void glFramebufferParameteri(GLenum target, GLenum pname, GLint param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.framebuffer_parameteri(ctx, target, pname, param);
}

void glGetFramebufferParameteriv(GLenum target, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_framebuffer_parameteriv(ctx, target, pname, params);
}

void glGetProgramInterfaceiv(GLuint program, GLenum programInterface, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_program_interfaceiv(ctx, program, programInterface, pname, params);
}

GLuint  glGetProgramResourceIndex(GLuint program, GLenum programInterface, const GLchar *name)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_program_resource_index(ctx, program, programInterface, name);
}

void glGetProgramResourceName(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_program_resource_name(ctx, program, programInterface, index, bufSize, length, name);
}

void glGetProgramResourceiv(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei count, GLsizei *length, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_program_resourceiv(ctx, program, programInterface, index, propCount, props, count, length, params);
}

GLint  glGetProgramResourceLocation(GLuint program, GLenum programInterface, const GLchar *name)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_program_resource_location(ctx, program, programInterface, name);
}

void glUseProgramStages(GLuint pipeline, GLbitfield stages, GLuint program)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.use_program_stages(ctx, pipeline, stages, program);
}

void glActiveShaderProgram(GLuint pipeline, GLuint program)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.active_shader_program(ctx, pipeline, program);
}

GLuint  glCreateShaderProgramv(GLenum type, GLsizei count, const GLchar *const*strings)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.create_shader_programv(ctx, type, count, strings);
}

void glBindProgramPipeline(GLuint pipeline)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_program_pipeline(ctx, pipeline);
}

void glDeleteProgramPipelines(GLsizei n, const GLuint *pipelines)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.delete_program_pipelines(ctx, n, pipelines);
}

void glGenProgramPipelines(GLsizei n, GLuint *pipelines)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.gen_program_pipelines(ctx, n, pipelines);
}

GLboolean  glIsProgramPipeline(GLuint pipeline)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_program_pipeline(ctx, pipeline);
}

void glGetProgramPipelineiv(GLuint pipeline, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_program_pipelineiv(ctx, pipeline, pname, params);
}

void glProgramUniform1i(GLuint program, GLint location, GLint v0)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform1i(ctx, program, location, v0);
}

void glProgramUniform2i(GLuint program, GLint location, GLint v0, GLint v1)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform2i(ctx, program, location, v0, v1);
}

void glProgramUniform3i(GLuint program, GLint location, GLint v0, GLint v1, GLint v2)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform3i(ctx, program, location, v0, v1, v2);
}

void glProgramUniform4i(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform4i(ctx, program, location, v0, v1, v2, v3);
}

void glProgramUniform1ui(GLuint program, GLint location, GLuint v0)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform1ui(ctx, program, location, v0);
}

void glProgramUniform2ui(GLuint program, GLint location, GLuint v0, GLuint v1)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform2ui(ctx, program, location, v0, v1);
}

void glProgramUniform3ui(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform3ui(ctx, program, location, v0, v1, v2);
}

void glProgramUniform4ui(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform4ui(ctx, program, location, v0, v1, v2, v3);
}

void glProgramUniform1f(GLuint program, GLint location, GLfloat v0)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform1f(ctx, program, location, v0);
}

void glProgramUniform2f(GLuint program, GLint location, GLfloat v0, GLfloat v1)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform2f(ctx, program, location, v0, v1);
}

void glProgramUniform3f(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform3f(ctx, program, location, v0, v1, v2);
}

void glProgramUniform4f(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform4f(ctx, program, location, v0, v1, v2, v3);
}

void glProgramUniform1iv(GLuint program, GLint location, GLsizei count, const GLint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform1iv(ctx, program, location, count, value);
}

void glProgramUniform2iv(GLuint program, GLint location, GLsizei count, const GLint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform2iv(ctx, program, location, count, value);
}

void glProgramUniform3iv(GLuint program, GLint location, GLsizei count, const GLint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform3iv(ctx, program, location, count, value);
}

void glProgramUniform4iv(GLuint program, GLint location, GLsizei count, const GLint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform4iv(ctx, program, location, count, value);
}

void glProgramUniform1uiv(GLuint program, GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform1uiv(ctx, program, location, count, value);
}

void glProgramUniform2uiv(GLuint program, GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform2uiv(ctx, program, location, count, value);
}

void glProgramUniform3uiv(GLuint program, GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform3uiv(ctx, program, location, count, value);
}

void glProgramUniform4uiv(GLuint program, GLint location, GLsizei count, const GLuint *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform4uiv(ctx, program, location, count, value);
}

void glProgramUniform1fv(GLuint program, GLint location, GLsizei count, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform1fv(ctx, program, location, count, value);
}

void glProgramUniform2fv(GLuint program, GLint location, GLsizei count, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform2fv(ctx, program, location, count, value);
}

void glProgramUniform3fv(GLuint program, GLint location, GLsizei count, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform3fv(ctx, program, location, count, value);
}

void glProgramUniform4fv(GLuint program, GLint location, GLsizei count, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform4fv(ctx, program, location, count, value);
}

void glProgramUniformMatrix2fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix2fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix3fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix3fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix4fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix4fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix2x3fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix2x3fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix3x2fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix3x2fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix2x4fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix2x4fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix4x2fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix4x2fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix3x4fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix3x4fv(ctx, program, location, count, transpose, value);
}

void glProgramUniformMatrix4x3fv(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.program_uniform_matrix4x3fv(ctx, program, location, count, transpose, value);
}

void glValidateProgramPipeline(GLuint pipeline)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.validate_program_pipeline(ctx, pipeline);
}

void glGetProgramPipelineInfoLog(GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_program_pipeline_info_log(ctx, pipeline, bufSize, length, infoLog);
}

void glBindImageTexture(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_image_texture(ctx, unit, texture, level, layered, layer, access, format);
}

void glGetBooleani_v(GLenum target, GLuint index, GLboolean *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_booleani_v(ctx, target, index, data);
}

void glMemoryBarrier(GLbitfield barriers)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.memory_barrier(ctx, barriers);
}

void glMemoryBarrierByRegion(GLbitfield barriers)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.memory_barrier_by_region(ctx, barriers);
}

void glTexStorage2DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_storage2_d_multisample(ctx, target, samples, internalformat, width, height, fixedsamplelocations);
}

void glGetMultisamplefv(GLenum pname, GLuint index, GLfloat *val)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_multisamplefv(ctx, pname, index, val);
}

void glSampleMaski(GLuint maskNumber, GLbitfield mask)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sample_maski(ctx, maskNumber, mask);
}

void glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_tex_level_parameteriv(ctx, target, level, pname, params);
}

void glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_tex_level_parameterfv(ctx, target, level, pname, params);
}

void glBindVertexBuffer(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.bind_vertex_buffer(ctx, bindingindex, buffer, offset, stride);
}

void glVertexAttribFormat(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_format(ctx, attribindex, size, type, normalized, relativeoffset);
}

void glVertexAttribIFormat(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_i_format(ctx, attribindex, size, type, relativeoffset);
}

void glVertexAttribBinding(GLuint attribindex, GLuint bindingindex)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_attrib_binding(ctx, attribindex, bindingindex);
}

void glVertexBindingDivisor(GLuint bindingindex, GLuint divisor)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.vertex_binding_divisor(ctx, bindingindex, divisor);
}

void glBlendBarrier()
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.blend_barrier(ctx, );
}

void glCopyImageSubData(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.copy_image_sub_data(ctx, srcName, srcTarget, srcLevel, srcX, srcY, srcZ, dstName, dstTarget, dstLevel, dstX, dstY, dstZ, srcWidth, srcHeight, srcDepth);
}

void glDebugMessageControl(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.debug_message_control(ctx, source, type, severity, count, ids, enabled);
}

void glDebugMessageInsert(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.debug_message_insert(ctx, source, type, id, severity, length, buf);
}

void glDebugMessageCallback(GLDEBUGPROC callback, const void *userParam)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.debug_message_callback(ctx, callback, userParam);
}

GLuint  glGetDebugMessageLog(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_debug_message_log(ctx, count, bufSize, sources, types, ids, severities, lengths, messageLog);
}

void glPushDebugGroup(GLenum source, GLuint id, GLsizei length, const GLchar *message)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.push_debug_group(ctx, source, id, length, message);
}

void glPopDebugGroup()
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.pop_debug_group(ctx, );
}

void glObjectLabel(GLenum identifier, GLuint name, GLsizei length, const GLchar *label)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.object_label(ctx, identifier, name, length, label);
}

void glGetObjectLabel(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_object_label(ctx, identifier, name, bufSize, length, label);
}

void glObjectPtrLabel(const void *ptr, GLsizei length, const GLchar *label)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.object_ptr_label(ctx, ptrlength, label);
}

void glGetObjectPtrLabel(const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_object_ptr_label(ctx, ptrbufSize, length, label);
}

void glGetPointerv(GLenum pname, void **params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_pointerv(ctx, pname, params);
}

void glEnablei(GLenum target, GLuint index)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.enablei(ctx, target, index);
}

void glDisablei(GLenum target, GLuint index)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.disablei(ctx, target, index);
}

void glBlendEquationi(GLuint buf, GLenum mode)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.blend_equationi(ctx, buf, mode);
}

void glBlendEquationSeparatei(GLuint buf, GLenum modeRGB, GLenum modeAlpha)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.blend_equation_separatei(ctx, buf, modeRGB, modeAlpha);
}

void glBlendFunci(GLuint buf, GLenum src, GLenum dst)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.blend_funci(ctx, buf, src, dst);
}

void glBlendFuncSeparatei(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.blend_func_separatei(ctx, buf, srcRGB, dstRGB, srcAlpha, dstAlpha);
}

void glColorMaski(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.color_maski(ctx, index, r, g, b, a);
}

GLboolean  glIsEnabledi(GLenum target, GLuint index)
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.is_enabledi(ctx, target, index);
}

void glDrawElementsBaseVertex(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_elements_base_vertex(ctx, mode, count, type, indicesbasevertex);
}

void glDrawRangeElementsBaseVertex(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_range_elements_base_vertex(ctx, mode, start, end, count, type, indicesbasevertex);
}

void glDrawElementsInstancedBaseVertex(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.draw_elements_instanced_base_vertex(ctx, mode, count, type, indicesinstancecount, basevertex);
}

void glFramebufferTexture(GLenum target, GLenum attachment, GLuint texture, GLint level)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.framebuffer_texture(ctx, target, attachment, texture, level);
}

void glPrimitiveBoundingBox(GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.primitive_bounding_box(ctx, minX, minY, minZ, minW, maxX, maxY, maxZ, maxW);
}

GLenum  glGetGraphicsResetStatus()
{
	GLMContext ctx = GET_CONTEXT();

	return ctx->dispatch.get_graphics_reset_status(ctx, );
}

void glReadnPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.readn_pixels(ctx, x, y, width, height, format, type, bufSize, data);
}

void glGetnUniformfv(GLuint program, GLint location, GLsizei bufSize, GLfloat *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.getn_uniformfv(ctx, program, location, bufSize, params);
}

void glGetnUniformiv(GLuint program, GLint location, GLsizei bufSize, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.getn_uniformiv(ctx, program, location, bufSize, params);
}

void glGetnUniformuiv(GLuint program, GLint location, GLsizei bufSize, GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.getn_uniformuiv(ctx, program, location, bufSize, params);
}

void glMinSampleShading(GLfloat value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.min_sample_shading(ctx, value);
}

void glPatchParameteri(GLenum pname, GLint value)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.patch_parameteri(ctx, pname, value);
}

void glTexParameterIiv(GLenum target, GLenum pname, const GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_parameter_iiv(ctx, target, pname, params);
}

void glTexParameterIuiv(GLenum target, GLenum pname, const GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_parameter_iuiv(ctx, target, pname, params);
}

void glGetTexParameterIiv(GLenum target, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_tex_parameter_iiv(ctx, target, pname, params);
}

void glGetTexParameterIuiv(GLenum target, GLenum pname, GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_tex_parameter_iuiv(ctx, target, pname, params);
}

void glSamplerParameterIiv(GLuint sampler, GLenum pname, const GLint *param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sampler_parameter_iiv(ctx, sampler, pname, param);
}

void glSamplerParameterIuiv(GLuint sampler, GLenum pname, const GLuint *param)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.sampler_parameter_iuiv(ctx, sampler, pname, param);
}

void glGetSamplerParameterIiv(GLuint sampler, GLenum pname, GLint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_sampler_parameter_iiv(ctx, sampler, pname, params);
}

void glGetSamplerParameterIuiv(GLuint sampler, GLenum pname, GLuint *params)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.get_sampler_parameter_iuiv(ctx, sampler, pname, params);
}

void glTexBuffer(GLenum target, GLenum internalformat, GLuint buffer)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_buffer(ctx, target, internalformat, buffer);
}

void glTexBufferRange(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_buffer_range(ctx, target, internalformat, buffer, offset, size);
}

void glTexStorage3DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
{
	GLMContext ctx = GET_CONTEXT();

	ctx->dispatch.tex_storage3_d_multisample(ctx, target, samples, internalformat, width, height, depth, fixedsamplelocations);
}

